// dart format width=80
// GENERATED BY DARTANTIC

part of 'user_test.dart';

// **************************************************************************
// ModelGenerator
// **************************************************************************

const DttModelMeta _dtt_User_fieldMeta = DttModelMeta(
  fields: {
    'name': DttFieldMeta(
      type: 'String',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'age': DttFieldMeta(
      type: 'int',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'email': DttFieldMeta(
      type: 'String',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'password': DttFieldMeta(
      type: 'String',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'isActive': DttFieldMeta(
      type: 'bool',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'createdAt': DttFieldMeta(
      type: 'DateTime',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'updatedAt': DttFieldMeta(
      type: 'DateTime?',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'nickname': DttFieldMeta(
      type: 'String?',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
  },
);

mixin _$UserMixin {
  static Map<String, dynamic> dttCreate({
    required String name,
    required int age,
    required String email,
    required String password,
    required bool isActive,
    required DateTime createdAt,
    DateTime? updatedAt,
    String? nickname,
  }) {
    final values = <String, dynamic>{
      'name': name,
      'age': age,
      'email': email,
      'password': password,
      'isActive': isActive,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
      'nickname': nickname,
    };
    final processedValues = dttPreprocess(values);
    dttValidate(processedValues);
    return dttPostprocess(processedValues);
  }

  static Map<String, dynamic> dttPreprocess(Map<String, dynamic> values) {
    // Preprocessing step - modify values before validation
    values['name'] = User._dttpreprocess_name(values['name']);
    values['email'] = User._dttpreprocess_email(values['email']);
    values['password'] = User._dttpreprocess_password(values['password']);
    return values;
  }

  static void dttValidateField_name(
    dynamic value,
    Map<String, dynamic> values,
  ) {
    if (value != null && !validateCustomLength(value)) {
      throw DttValidationError('name', 'name failed custom validation');
    }
    if (value != null && value.length < 2) {
      throw DttValidationError('name', 'name must be at least 2 characters');
    }
    if (value != null && !User._dttvalidate_name(value)) {
      throw DttValidationError('name', 'name failed custom validation');
    }
  }

  static void dttValidateField_age(dynamic value, Map<String, dynamic> values) {
    if (value == null) {
      throw DttValidationError('age', 'age is required');
    }
    if (value != null && !User._dttvalidate_age(value)) {
      throw DttValidationError('age', 'age failed custom validation');
    }
  }

  static void dttValidateField_email(
    dynamic value,
    Map<String, dynamic> values,
  ) {
    if (value != null && !validateEmailFormat(value)) {
      throw DttValidationError('email', 'email failed custom validation');
    }
    if (value != null && value.length < 5) {
      throw DttValidationError('email', 'email must be at least 5 characters');
    }
    if (value != null && value.length > 50) {
      throw DttValidationError('email', 'email must be at most 50 characters');
    }
    if (value != null && !User._dttvalidate_email(value, values)) {
      throw DttValidationError('email', 'email failed custom validation');
    }
  }

  static void dttValidateField_password(
    dynamic value,
    Map<String, dynamic> values,
  ) {
    if (value != null && !validateStrongPassword(value)) {
      throw DttValidationError('password', 'password failed custom validation');
    }
    if (value != null && value.length < 8) {
      throw DttValidationError(
        'password',
        'password must be at least 8 characters',
      );
    }
  }

  static void dttValidateField_isActive(
    dynamic value,
    Map<String, dynamic> values,
  ) {}
  static void dttValidateField_createdAt(
    dynamic value,
    Map<String, dynamic> values,
  ) {}
  static void dttValidateField_updatedAt(
    dynamic value,
    Map<String, dynamic> values,
  ) {}
  static void dttValidateField_nickname(
    dynamic value,
    Map<String, dynamic> values,
  ) {
    if (value != null && value.length < 3) {
      throw DttValidationError(
        'nickname',
        'nickname must be at least 3 characters',
      );
    }
  }

  static void dttValidate(Map<String, dynamic> values) {
    if (values['name'] != null) dttValidateField_name(values['name'], values);
    if (values['age'] != null) dttValidateField_age(values['age'], values);
    if (values['email'] != null)
      dttValidateField_email(values['email'], values);
    if (values['password'] != null)
      dttValidateField_password(values['password'], values);
    if (values['isActive'] != null)
      dttValidateField_isActive(values['isActive'], values);
    if (values['createdAt'] != null)
      dttValidateField_createdAt(values['createdAt'], values);
    if (values['updatedAt'] != null)
      dttValidateField_updatedAt(values['updatedAt'], values);
    if (values['nickname'] != null)
      dttValidateField_nickname(values['nickname'], values);
  }

  static Map<String, dynamic> dttPostprocess(Map<String, dynamic> values) {
    // Postprocessing step - modify values after validation
    values['createdAt'] = User._dttpostprocess_createdAt(values['createdAt']);
    values['isActive'] = User._dttpostprocess_isActive(values['isActive']);
    return values;
  }

  static Map<String, dynamic> dttFromMap(Map<String, dynamic> map) {
    // Process and validate map data (including nested models)
    final processedMap = <String, dynamic>{
      'name': map['name'],
      'age': map['age'],
      'email': map['email'],
      'password': map['password'],
      'isActive': map['isActive'],
      'createdAt': map['createdAt'],
      'updatedAt': map['updatedAt'],
      'nickname': map['nickname'],
    };
    // Apply preprocessing, validation, and postprocessing to the processed map
    final preprocessed = dttPreprocess(processedMap);
    dttValidate(preprocessed);
    return dttPostprocess(preprocessed);
  }

  static Map<String, dynamic> dttToMap(User obj) {
    // Convert object instance to a map
    return {
      'name': obj.name,
      'age': obj.age,
      'email': obj.email,
      'password': obj.password,
      'isActive': obj.isActive,
      'createdAt': obj.createdAt,
      'updatedAt': obj.updatedAt,
      'nickname': obj.nickname,
    };
  }
}

const DttModelMeta _dtt_Profile_fieldMeta = DttModelMeta(
  fields: {
    'bio': DttFieldMeta(
      type: 'String',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'website': DttFieldMeta(
      type: 'String?',
      isFinal: true,
      isLate: false,
      subModel: null,
    ),
    'user': DttFieldMeta(
      type: 'User',
      isFinal: true,
      isLate: false,
      subModel: 'User',
    ),
  },
);

mixin _$ProfileMixin {
  static Map<String, dynamic> dttCreate({
    required String bio,
    String? website,
    required User user,
  }) {
    final values = <String, dynamic>{
      'bio': bio,
      'website': website,
      'user': user,
    };
    final processedValues = dttPreprocess(values);
    dttValidate(processedValues);
    return dttPostprocess(processedValues);
  }

  static Map<String, dynamic> dttPreprocess(Map<String, dynamic> values) {
    // Preprocessing step - modify values before validation
    values['bio'] = Profile._dttpreprocess_bio(values['bio']);
    return values;
  }

  static void dttValidateField_bio(dynamic value, Map<String, dynamic> values) {
    if (value == null) {
      throw DttValidationError('bio', 'bio is required');
    }
    if (value != null && value.length < 1) {
      throw DttValidationError('bio', 'bio must be at least 1 characters');
    }
  }

  static void dttValidateField_website(
    dynamic value,
    Map<String, dynamic> values,
  ) {
    if (value != null && value.length < 3) {
      throw DttValidationError(
        'website',
        'website must be at least 3 characters',
      );
    }
    if (value != null && value.length > 20) {
      throw DttValidationError(
        'website',
        'website must be at most 20 characters',
      );
    }
    if (value != null && !Profile._dttvalidate_website(value)) {
      throw DttValidationError('website', 'website failed custom validation');
    }
  }

  static void dttValidateField_user(
    dynamic value,
    Map<String, dynamic> values,
  ) {}
  static void dttValidate(Map<String, dynamic> values) {
    if (values['bio'] != null) dttValidateField_bio(values['bio'], values);
    if (values['website'] != null)
      dttValidateField_website(values['website'], values);
    if (values['user'] != null) dttValidateField_user(values['user'], values);
  }

  static Map<String, dynamic> dttPostprocess(Map<String, dynamic> values) {
    // Postprocessing step - modify values after validation
    // No postprocessing methods found
    return values;
  }

  static Map<String, dynamic> dttFromMap(Map<String, dynamic> map) {
    // Process and validate map data (including nested models)
    final processedMap = <String, dynamic>{
      'bio': map['bio'],
      'website': map['website'],
      'user': _$UserMixin.dttFromMap(map['user'] as Map<String, dynamic>),
    };
    // Apply preprocessing, validation, and postprocessing to the processed map
    final preprocessed = dttPreprocess(processedMap);
    dttValidate(preprocessed);
    return dttPostprocess(preprocessed);
  }

  static Map<String, dynamic> dttToMap(Profile obj) {
    // Convert object instance to a map
    return {
      'bio': obj.bio,
      'website': obj.website,
      'user': _$UserMixin.dttToMap(obj.user),
    };
  }
}
